modelname: blip2-pretrained
_target_: src.model.blip2_cir.blip2_cir

ckpt_path: ${model.ckpt.path}

model:
  _target_: src.model.blip2_cir.Blip2Qformer
  med_config: ${paths.work_dir}/configs/med_config.json
  image_size: ${data.image_size}
  vit: "large"
  vit_grad_ckpt: False
  vit_ckpt_layer: 12
  embed_dim: 256
  train_vit: False
  loss: ${model.loss}
