modelname: blip2
_target_: src.model.blip2_cir.blip2_cir

ckpt_path: ${model.ckpt.path}

model:
  _target_: src.model.blip2_cir.BLIP2Cir
  vit_model: "eva_clip_g"
  img_size: ${data.image_size}
  num_query_token: 32
  cross_attention_freq: 2
  embed_dim: 256
  max_txt_len: 32
  freeze_vit: True
  use_grad_checkpoint: False
  drop_path_rate: 0
  vit_precision: "fp16"
  loss: ${model.loss}
