name: blip2

path: "https://storage.googleapis.com/sfr-vision-language-research/LAVIS/models/BLIP2/blip2_pretrained.pth"
# path: "https://storage.googleapis.com/sfr-vision-language-research/LAVIS/models/BLIP2/blip2_finetune_coco.pth"
# path: "/home/hualin2/CV806-Project/outputs/cirr/blip2/blip2/tv-loss-hnnce_lr-0.0001/base/ckpt_last.ckpt"